language: python
python:
  - "2.7"
cache: pip
install:
  - pip install coverage
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - coverage run python test2.py
after_success:
  - coverage report
  - coveralls